### PR TITLE
defer close tcp connection for mgmt calls

### LINKED ISSUE #111: Potential socket leak in amqp connection
https://github.com/Azure/azure-event-hubs-go/blob/95f9bc025a9462337f8087aa883bc9b35a1e693e/hub.go#L490

https://github.com/Azure/azure-event-hubs-go/blob/95f9bc025a9462337f8087aa883bc9b35a1e693e/hub.go#L510

We have a loop that calls `GetRuntimeInformation` to get a list of `PartitionIDs`. We've noticed that the number of sockets increases until the program crashes with `socket: too many open files`. These `newConnection` calls call `amqp.Dial()` which is not being closed. I believe you need `defer c.Close()` after each of these `newConnection` calls. 

### Expected Behavior

The number of TCP connections opened by the program should stay constant over time.

### Actual Behavior

The number of TCP connections is increasing unbounded.

### Environment
- OS: Darwin Kernel Version 18.2.0
- Go version:  go1.12.5 darwin/amd64
- Version of Library: github.com/Azure/azure-event-hubs-go v1.3.0

### PR DESCRIPTION
**Pull request by devigned**
### Fix or Enhancement?
fixes #111 

- [x] All tests passed
- [x] Add change to `changelog.md`

### CODE REVIEW

File: hub.go [hunk 1]
```diff
@@ -488,6 +488,14 @@ func (h *Hub) GetRuntimeInformation(ctx context.Context) (*HubRuntimeInformation
 	defer span.End()
 	client := newClient(h.namespace, h.name)
 	c, err := h.namespace.newConnection()
+	if c != nil {
```
Comment (vcabbage) [inline hub.go]: Is it possible for `c` to be valid when `err != nil`? In common usage it's assumed that the first value shouldn't be used in any way if `err != nil` and a defer would typically be placed after the error check. (Unless documented otherwise.)

Comment (devigned) [reply hub.go]: Awesome question. I wasn't sure if c.start() should return something that raises an error, but still needed to be closed. Having now dug deeper, it appears that if an error is returned below, you are doing the right thing by closing c.

Thank you for the catch. I will make the change.
